spring.application.name=student-semester-enrollment
axon.axonserver.enabled=false
spring.jpa.open-in-view=false

# Kafka local
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.acks=all
spring.kafka.consumer.group-id=student_semester_enrollment
spring.kafka.consumer.auto-offset-reset=earliest

# Database local
spring.datasource.url=jdbc:postgresql://localhost:5445/student_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# Hikari
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Server
server.port=8094

# Consul local
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500

spring.cloud.consul.config.enabled=false
spring.cloud.consul.config.import-check.enabled=false

spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.service-name=student-semester-enrollment
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.health-check-interval=10s
spring.cloud.consul.discovery.prefer-ip-address=true

spring.cloud.loadbalancer.enabled=true

# Circuit Breaker
resilience4j.circuitbreaker.instances.studentManagement.slidingWindowSize=10
resilience4j.circuitbreaker.instances.studentManagement.failureRateThreshold=50
resilience4j.circuitbreaker.instances.studentManagement.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.studentManagement.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.studentManagement.automaticTransitionFromOpenToHalfOpenEnabled=true

resilience4j.circuitbreaker.instances.subjectManagement.slidingWindowSize=10
resilience4j.circuitbreaker.instances.subjectManagement.failureRateThreshold=50
resilience4j.circuitbreaker.instances.subjectManagement.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.subjectManagement.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.subjectManagement.automaticTransitionFromOpenToHalfOpenEnabled=true

spring.cloud.openfeign.circuitbreaker.enabled=true
spring.cloud.openfeign.circuitbreaker.group.enabled=true

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/docs

# Springwolf
springwolf.enabled=true
springwolf.docket.base-package=mk.ukim.finki.student_semester_enrollment
springwolf.docket.info.title=Student Semester Enrollment Events
springwolf.docket.info.version=1.0.0
springwolf.docket.info.description=Kafka events published by student semester enrollment service
springwolf.docket.servers.kafka.protocol=kafka
springwolf.docket.servers.kafka.host=localhost:9092